// <auto-generated />
namespace EntityAcessoDados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Set_Usuario_Login_Unique : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Set_Usuario_Login_Unique));
        
        string IMigrationMetadata.Id
        {
            get { return "201810012114053_Set_Usuario_Login_Unique"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
