// <auto-generated />
namespace EntityAcessoDados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class create_and_cartao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_and_cartao));
        
        string IMigrationMetadata.Id
        {
            get { return "201810251318271_create_and_cartao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
