// <auto-generated />
namespace EntityAcessoDados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreateTables_Pessoa_Usuario_Cartao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateTables_Pessoa_Usuario_Cartao));
        
        string IMigrationMetadata.Id
        {
            get { return "201809302112123_CreateTables_Pessoa_Usuario_Cartao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
