// <auto-generated />
namespace EntityAcessoDados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class receita : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(receita));
        
        string IMigrationMetadata.Id
        {
            get { return "201811111440331_receita"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
