// <auto-generated />
namespace EntityAcessoDados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Change_Type_Id_Pessoa_Usuario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_Type_Id_Pessoa_Usuario));
        
        string IMigrationMetadata.Id
        {
            get { return "201810041128461_Change_Type_Id_Pessoa_Usuario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
