// <auto-generated />
namespace EntityAcessoDados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dash_minto_cartao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dash_minto_cartao));
        
        string IMigrationMetadata.Id
        {
            get { return "201811091554294_dash_minto_cartao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
